version: '3'
services:
  app:
    build: ./
    volumes:
      - "./:/app:cached"
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=sqlsrv
      - DB_HOST=db
      - DB_PORT=1433
      - DB_DATABASE=starling_dev
      - DB_USERNAME=SA
      - DB_PASSWORD=St@rl1n9
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux:2017-CU12
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=St@rl1n9